auth:
  rootUser: "minioadmin"
  rootPassword: "minioadmin_password"

# Création automatique des buckets pour Mimir et Loki
defaultBuckets: "mimir-blocks,mimir-ruler,loki-data,loki-ruler"

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 50Gi
