auth:
  rootUser: "admin"
  rootPassword: "admin"

# Création automatique des buckets pour Mimir et Loki
defaultBuckets: "mimir-blocks,mimir-ruler,loki-data,loki-ruler"

persistence:
  enabled: true
  storageClass: "longhorn-prod"
  size: 10Gi

image:
  registry: docker.io
  repository: bitnamilegacy/minio
  tag: 2025.7.23-debian-12-r3
