apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: "1.6.2"
    releaseName: longhorn
    namespace: longhorn-system
    valuesInline:
      preUpgradeChecker:
        jobEnabled: false
      persistence:
        defaultClass: false
        defaultClassReplicaCount: 3
      defaultSettings:
        backupstorageMinimalAvailablePercentage: 10
        createDefaultDiskLabeledNodes: true
        disableSchedulingOnCordonedNode: "true"
        replicaSoftAntiAffinity: "true"
      csi:
        attacherReplicaCount: 1
        provisionerReplicaCount: 1
        resizerReplicaCount: 1
        snapshotterReplicaCount: 1
      ui:
        enabled: true
        replicas: 1
      ingress:
        enabled: false
