apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-server-tls
spec:
  secretName: minio-server-tls
  issuerRef:
    name: observability-issuer
    kind: Issuer
  dnsNames:
    - minio
    - minio.observability
    - minio.observability.svc
    - minio.observability.svc.cluster.local
