apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: minio-root-creds
    type: Opaque
    literals:
      - username=admin
      - password=admin
    options:
      disableNameSuffixHash: true # Pour garder le nom exact 'minio-root-creds'

helmCharts:
  - name: tenant
    repo: https://operator.min.io/
    version: 7.1.1
    releaseName: minio-tenant
    namespace: observability
    valuesFile: values.yaml
