tenant:
  name: minio

  configuration:
    name: minio-root-creds

  configSecret:
    name: minio-root-creds
    existingSecret: true

  certificate:
    requestAutoCert: false

  buckets:
    - name: loki-data
    - name: loki-ruler
    - name: mimir-data
    - name: mimir-ruler

  pools:
    - name: data
      servers: 1
      volumesPerServer: 2
      size: 5Gi
      storageClassName: longhorn-prod
