apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: victoria-metrics-single
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.12.5
    releaseName: victoria-metrics
    namespace: observability
    valuesFile: values.yaml
