server:
  replicaCount: 1
  retentionPeriod: "7"

  persistentVolume:
    enabled: true
    storageClass: longhorn-observability
    size: 8Gi

  podSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000

  containerSecurityContext:
    enabled: true
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

  extraArgs:
    memory.allowedPercent: "80"
    loggerFormat: json

rbac:
  create: true

serviceAccount:
  create: true

serviceMonitor:
  enabled: false