apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-gateway-tls
  namespace: ingress-gateway
spec:
  secretName: internal-gateway-tls
  issuerRef:
    name: main-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.internal.cluster.local"
