apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/cascade-delete
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/combarim/gitops-test.git
        revision: main
        files:
          - path: "apps/core/*/config.json"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-mgmt'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{default "0" .syncWave}}'
    spec:
      project: core-infrastructure
      source:
        repoURL: https://github.com/combarim/gitops-test.git
        targetRevision: main
        path: 'apps/core/{{.path.basenameNormalized}}/overlays/mgmt'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - ServerSideApply=true