mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio.observability.svc:443
          access_key_id: ${MINIO_ACCESS_KEY}
          secret_access_key: ${MINIO_SECRET_KEY}
          insecure: false
          http:
            tls_config:
              ca_file: /etc/mimir/certs/ca.crt
            insecure_skip_verify: false
    blocks_storage:
      s3:
        bucket_name: mimir-data
    alertmanager_storage:
      s3:
        bucket_name: mimir-ruler
    ruler_storage:
      s3:
        bucket_name: mimir-ruler


gateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
  nginx:
    config:
      resolver: rke2-coredns-rke2-coredns.kube-system.svc.cluster.local.

global:
  extraEnv:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-root-creds
          key: username
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-root-creds
          key: password
  extraVolumes:
    - name: root-ca
      secret:
        secretName: observability-ca-bundle
        items:
          - key: tls.crt
            path: ca.crt
  extraVolumeMounts:
    - name: root-ca
      mountPath: /etc/mimir/certs
      readOnly: true

enterprise:
  enabled: false

rollout_operator:
  enabled: false

ingester:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  persistentVolume:
    size: 2Gi

querier:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

query_frontend:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

distributor:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

compactor:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi

store_gateway:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi
  persistentVolume:
    size: 2Gi

ruler:
  enabled: false

minio:
  enabled: false
