mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio.observability.svc:443
          access_key_id: ${MINIO_ACCESS_KEY}
          secret_access_key: ${MINIO_SECRET_KEY}
          insecure: false
          force_path_style: true
          http_config:
            ca_file: /etc/mimir/certs/ca.crt
    blocks_storage:
      storage_prefix: mimir
      s3:
        bucket_name: mimir-data
    alertmanager_storage:
      storage_prefix: alertmanager
      s3:
        bucket_name: mimir-ruler
    ruler_storage:
      storage_prefix: ruler
      s3:
        bucket_name: mimir-ruler

gateway:
  enabled: true
  nginx:
    config:
      resolver: rke2-coredns-rke2-coredns.kube-system.svc.cluster.local.

global:
  extraEnv:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-root-creds
          key: username
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-root-creds
          key: password
  extraVolumes:
    - name: root-ca
      secret:
        secretName: minio-server-tls
  extraVolumeMounts:
    - name: root-ca
      mountPath: /etc/mimir/certs
      readOnly: true

enterprise:
  enabled: false

rollout_operator:
  enabled: false

ingester:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

querier:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

query_frontend:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

distributor:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

compactor:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

store_gateway:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

minio:
  enabled: false
