loki:
  auth_enabled: false
  deploymentMode: SimpleScalable
  
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio.observability.svc:80
      accessKeyId: ${MINIO_ACCESS_KEY}
      secretAccessKey: ${MINIO_SECRET_KEY}
      s3ForcePathStyle: true
      insecure: true

  structuredConfig:
    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    limits_config:
      retention_period: 168h
      allow_structured_metadata: true

    compactor:
      working_directory: /var/loki/compactor
      retention_enabled: true
      delete_request_store: s3

  extraArgs:
    - -config.expand-env=true

global:
  extraEnv:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-root-creds
          key: username
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-root-creds
          key: password

gateway:
  enabled: true
  replicas: 1
  nginxConfig:
    resolver: rke2-coredns-rke2-coredns.kube-system.svc.cluster.local


write:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn-observability
    size: 5Gi

read:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn-observability
    size: 2Gi

backend:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn-observability
    size: 2Gi

chunksCache:
  enabled: false

resultsCache:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
  serviceMonitor:
    enabled: false