apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-store
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    infisical:
      hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-bootstrap-credentials
            namespace: infisical
            key: accessToken
      secretsScope:
        projectSlug: inforisk
        environmentSlug: mgmt
        secretPath: "/"
