apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: github-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    github:
      auth:
        token:
          secretRef:
            name: github-pat
            namespace: external-secrets
            key: token
      owner: combarim
      repository: gitops-test
