apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 0.13.1
    releaseName: grafana-alloy
    namespace: observability
    valuesFile: values.yaml
