apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml
  - rbac.yaml

helmCharts:
  - name: infisical-standalone
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    version: 1.8.0
    releaseName: infisical
    namespace: infisical
    valuesFile: values.yaml
