infisical:
  enabled: true
  replicaCount: 1
  image:
    repository: infisical/infisical
    tag: "v0.159.24"

  serviceAccount:
    create: false
    name: infisical-bootstrap-sa

  autoBootstrap:
    enabled: true
    organization: "inforisk"
    secretDestination:
      name: "infisical-bootstrap-credentials"
      namespace: "infisical"
    secretTemplate: '{"data":{"accessToken":"{{.Identity.Credentials.Token}}"}}'

  extraEnv:
    - name: INFISICAL_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: infisical-master-key
          key: key
    - name: INFISICAL_SERVER_SITE_URL
      value: "https://infisical.internal.inforisk.ma"

postgresql:
  enabled: true
  auth:
    username: infisical
    database: infisicalDB
    existingSecret: infisical-postgres-secret
  primary:
    persistence:
      storageClass: longhorn-observability

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: infisical-redis-secret
  master:
    persistence:
      storageClass: longhorn-observability

ingress:
  enabled: false
