infisical:
  enabled: true
  replicaCount: 1
  image:
    repository: infisical/infisical
    tag: "v0.158.0"
  kubeSecretRef: "infisical-secrets"
  autoBootstrap:
    enabled: true
    organization: "inforisk"
    secretDestination:
      name: "infisical-bootstrap-credentials"
      namespace: "infisical"
    # Formate la clé en "accessToken" pour correspondre au champ attendu par ESO
    secretTemplate: '{"stringData":{"accessToken":"{{.Identity.Credentials.Token}}"}}'

postgresql:
  enabled: true
  auth:
    username: infisical
    database: infisicalDB
    existingSecret: infisical-secrets
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    persistence:
      storageClass: longhorn-observability

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      storageClass: longhorn-observability
