infisical:
  enabled: true
  replicaCount: 1
  image:
    repository: infisical/infisical
    tag: "v0.159.24"
  kubeSecretRef: "infisical-secrets"
  autoBootstrap:
    enabled: true
    organization: "inforisk"
    secretDestination:
      name: "infisical-bootstrap-credentials"
      namespace: "infisical"
    secretTemplate: '{"stringData":{"accessToken":"{{.Identity.Credentials.Token}}"}}'

postgresql:
  enabled: true
  auth:
    username: infisical
    database: infisicalDB
    password: root
  primary:
    persistence:
      storageClass: longhorn-observability

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      storageClass: longhorn-observability

ingress-nginx:
  enabled: false
