apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: observability-ca
  namespace: observability
spec:
  isCA: true
  commonName: "Observability Intermediate CA"
  secretName: observability-ca-bundle
  issuerRef:
    name: main-ca-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: observability-issuer
  namespace: observability
spec:
  ca:
    secretName: observability-ca-bundle
