apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
spec:
  parentRefs:
    - name: internal-gateway
      namespace: ingress-gateway
  hostnames:
    - argocd.internal.inforisk.ma
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80
