apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
spec:
  parentRefs:
    - kind: Gateway
      name: internal-gateway
      namespace: ingress-gateway
  hostnames:
    - argocd.internal.inforisk.ma
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 80
