apiVersion: v1
kind: Secret
metadata:
  name: minio-root-creds
  namespace: observability
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER=minio-admin-daf0e76d
    export MINIO_ROOT_PASSWORD=zD8juNScClssQe7X2cXr9lfvc3PttUIF
  username: minio-admin-daf0e76d
  password: zD8juNScClssQe7X2cXr9lfvc3PttUIF
