apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-creds
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: github-secret-store
  target:
    name: minio-root-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config.env: |
          export MINIO_ROOT_USER={{ .username }}
          export MINIO_ROOT_PASSWORD={{ .password }}
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: password
      remoteRef:
        key: MINIO_ROOT_PASSWORD
