apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb

resources:
  - namespace.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: "0.14.9"
    releaseName: metallb
    namespace: metallb
    valuesInline:
      metallb:
        controller:
          tolerations: []
        speaker:
          tolerations: []
