---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: Core infrastructure components (networking, storage, PKI, ingress)
  sourceRepos:
    - https://github.com/combarim/gitops-test.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Business workloads and applications
  sourceRepos:
    - https://github.com/combarim/gitops-test.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  # Workloads ne peuvent PAS créer de ressources cluster-wide
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
